updateMessage: true
locale:
  lang: en
  country: GB
default:
  autosort: false
  pattern: LEFT_TO_RIGHT_TOP_TO_BOTTOM
  categories:
    - AlphaBackAsc
    - IsBlock
  sorting:
    notification: true
    sound:
      active: true
      name: ENTITY_PIG_SADDLE
      volume: '2.0'
      pitch: '2.0'
  refill:
    blocks: true
    consumables: true
    breakables: true
  clicksort: true
cleaningItem:
  active: true
  durability: true
  openEvent: true
  item:
    ==: org.bukkit.inventory.ItemStack
    v: 2230
    type: IRON_HOE
cooldown:
  active: true
  time: 5000
blacklist:
  stacking:
    - air
  inventory:
    - furnace
categories:
  words:
    - ==: WordCategory
      name: StoneWord
      word: stone
    - ==: WordCategory
      name: StairWord
      word: stair
    - ==: WordCategory
      name: SlabWord
      word: slab
    - ==: WordCategory
      name: CarpetWord
      word: carpet
  lists:
    - ==: ListCategory
      name: StoneList
      list:
        - stone
        - stone_bricks
        - mossy_stone_bricks
        - cracked_stone_bricks
        - chiseled_stone_bricks
        - smooth_stone
        - granite
        - polished_granite
        - diorite
        - polished_diorite
        - andesite
        - polished_andesite
        - gravel
    - ==: ListCategory
      name: DirtList
      list:
        - dirt
        - grass_block
        - grass_path
        - coarse_dirt
        - podzol
        - mycelium
  master:
    - ==: MasterCategory
      name: StoneMaster
      list:
        - StoneList
        - StoneWord
